[package]
name = "rscsv"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.7", features = ["derive"] }
csv = "1.3.0"
prettytable-rs = "0.10.0"
regex = "1.11.1"
